/* Generated by Cython 0.26 */

#ifndef __PYX_HAVE__pyregina
#define __PYX_HAVE__pyregina


#ifndef __PYX_HAVE_API__pyregina

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int action(regina::NTriangulation &);

#endif /* !__PYX_HAVE_API__pyregina */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initpyregina(void);
#else
PyMODINIT_FUNC PyInit_pyregina(void);
#endif

#endif /* !__PYX_HAVE__pyregina */
